# traefik-reverse-proxy: SSL, reverse proxy to apache2
# apache2: Tequila, static files, reverse proxy to gunicorn
# gunicon: Django app, static files production

services:
  traefik-reverse-proxy:
    image: traefik:v3.3
    restart: unless-stopped
    command:
      - "--providers.docker"
      - "--providers.file.directory=/configuration/"
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/configuration/traefik.yml
      - ${SSL_CERT_CRT:-./cert/certificate.crt}:/cert/certificate.crt
      - ${SSL_CERT_KEY:-./cert/certificate.key}:/cert/certificate.key

  apache2:
    build: apache2
    volumes:
      - ./apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache2/oidc.secret.conf:/usr/local/apache2/conf/oidc.secret.conf
      - static:/app/static:ro
    labels:
      - "traefik.http.routers.enacdrives_apache2.tls=true"
      - "traefik.http.routers.enacdrives_apache2.rule=PathPrefix(`/`)"
      - "traefik.http.routers.enacdrives_apache2_http.tls=false"
      - "traefik.http.routers.enacdrives_apache2_http.rule=PathPrefix(`/`)"
      - "traefik.http.services.enacdrives_apache2.loadbalancer.server.port=80"

  gunicorn:
    build: .
    volumes:
      - static:/app/static
      - installers:/app/installers
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000

  db:
    image: mysql
    restart: unless-stopped
    env_file:
      - .secrets.env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 2s
      timeout: 2s
      retries: 15

  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080

volumes:
  mysql:
    driver: local
  static:
    driver: local
  installers:
    driver: local
