# Apache -> SSL + Tequila + reverse proxy
# uvicorn -> Django

version: '3.1'
services:
  apache2:
    build: apache-tequila
    volumes:
      - ./static:/app/static
      - django-installers:/app/installers
    ports:
      - 80:80
      - 443:443

  gunicorn:
    build: .
    volumes:
      - django-installers:/app/installers
    ports:
      - 8000:8000

  db:
    image: mysql
    restart: unless-stopped
    env_file:
      - .secrets.env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  mysql:
    driver: local
  django-installers:
    driver: local
