# Apache -> SSL + Tequila + reverse proxy
# uvicorn -> Django

version: "3.1"
services:
  apache2:
    build: apache2
    volumes:
      - static:/app/static:ro
      - installers:/app/installers:ro
    ports:
      - 80:80

  gunicorn:
    build: .
    volumes:
      - static:/app/static
      - installers:/app/installers
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: mysql
    restart: unless-stopped
    env_file:
      - .secrets.env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  mysql:
    driver: local
  static:
    driver: local
  installers:
    driver: local
