# traefik-reverse-proxy: SSL, reverse proxy to apache2
# apache2: Tequila, static files, reverse proxy to gunicorn
# gunicon: Django app, static files production

version: "3.1"
services:
  traefik-reverse-proxy:
    image: traefik:v3.0
    restart: unless-stopped
    command:
      - "--providers.docker"
      - "--providers.file.directory=/configuration/"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/configuration/traefik.yml
      - ${SSL_CERT_CRT:-./cert/certificate.crt}:/cert/certificate.crt
      - ${SSL_CERT_KEY:-./cert/certificate.key}:/cert/certificate.key

  apache2:
    build: apache2
    volumes:
      - static:/app/static:ro
      - installers:/app/installers:ro
    labels:
      - "traefik.http.routers.enac_cd_app.tls=true"
      - "traefik.http.routers.enac_cd_app.rule=PathPrefix(`/`)"
      - "traefik.http.services.enac_cd_app.loadbalancer.server.port=80"

  gunicorn:
    build: .
    volumes:
      - static:/app/static
      - installers:/app/installers
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: mysql
    restart: unless-stopped
    env_file:
      - .secrets.env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  mysql:
    driver: local
  static:
    driver: local
  installers:
    driver: local
