version: '3.1'

services:

  db:
    image: mysql
    restart: unless-stopped
    env_file:
      - .secrets.env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  mysql:
    driver: local
